//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace DeKee.DomainContext.Services.Dto
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", ElementName ="TransferTo", IsNullable = false)]
    public partial class CheckResponse
    {

        private string countryField;

        private ushort countryidField;

        private string operatorField;

        private ushort operatoridField;

        private byte connection_statusField;

        private string destination_msisdnField;

        private string destination_currencyField;

        private string product_listField;

        private string service_fee_listField;

        private string retail_price_listField;

        private string wholesale_price_listField;

        private string local_info_value_listField;

        private string local_info_amount_listField;

        private string local_info_currencyField;

        private ulong authentication_keyField;

        private string error_codeField;

        private string error_txtField;

        /// <remarks/>
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public ushort countryid
        {
            get
            {
                return this.countryidField;
            }
            set
            {
                this.countryidField = value;
            }
        }

        /// <remarks/>
        public string @operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }

        /// <remarks/>
        public ushort operatorid
        {
            get
            {
                return this.operatoridField;
            }
            set
            {
                this.operatoridField = value;
            }
        }

        /// <remarks/>
        public byte connection_status
        {
            get
            {
                return this.connection_statusField;
            }
            set
            {
                this.connection_statusField = value;
            }
        }

        /// <remarks/>
        public string destination_msisdn
        {
            get
            {
                return this.destination_msisdnField;
            }
            set
            {
                this.destination_msisdnField = value;
            }
        }

        /// <remarks/>
        public string destination_currency
        {
            get
            {
                return this.destination_currencyField;
            }
            set
            {
                this.destination_currencyField = value;
            }
        }

        /// <remarks/>
        public string product_list
        {
            get
            {
                return this.product_listField;
            }
            set
            {
                this.product_listField = value;
            }
        }

        /// <remarks/>
        public string service_fee_list
        {
            get
            {
                return this.service_fee_listField;
            }
            set
            {
                this.service_fee_listField = value;
            }
        }

        /// <remarks/>
        public string retail_price_list
        {
            get
            {
                return this.retail_price_listField;
            }
            set
            {
                this.retail_price_listField = value;
            }
        }

        /// <remarks/>
        public string wholesale_price_list
        {
            get
            {
                return this.wholesale_price_listField;
            }
            set
            {
                this.wholesale_price_listField = value;
            }
        }

        /// <remarks/>
        public string local_info_value_list
        {
            get
            {
                return this.local_info_value_listField;
            }
            set
            {
                this.local_info_value_listField = value;
            }
        }

        /// <remarks/>
        public string local_info_amount_list
        {
            get
            {
                return this.local_info_amount_listField;
            }
            set
            {
                this.local_info_amount_listField = value;
            }
        }

        /// <remarks/>
        public string local_info_currency
        {
            get
            {
                return this.local_info_currencyField;
            }
            set
            {
                this.local_info_currencyField = value;
            }
        }

        /// <remarks/>
        public ulong authentication_key
        {
            get
            {
                return this.authentication_keyField;
            }
            set
            {
                this.authentication_keyField = value;
            }
        }

        /// <remarks/>
        public string error_code
        {
            get
            {
                return this.error_codeField;
            }
            set
            {
                this.error_codeField = value;
            }
        }

        /// <remarks/>
        public string error_txt
        {
            get
            {
                return this.error_txtField;
            }
            set
            {
                this.error_txtField = value;
            }
        }
    }
}