//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace DeKee.DomainContext.Services.Dto
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", ElementName ="Xml", IsNullable = false)]
    public partial class CheckRequest
    {

        private string loginField;

        private uint keyField;

        private string md5Field;

        private string destination_msisdnField;

        private byte delivered_amount_infoField;

        private byte return_service_feeField;

        private string actionField;

        /// <remarks/>
        public string login
        {
            get
            {
                return this.loginField;
            }
            set
            {
                this.loginField = value;
            }
        }

        /// <remarks/>
        public uint key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        public string md5
        {
            get
            {
                return this.md5Field;
            }
            set
            {
                this.md5Field = value;
            }
        }

        /// <remarks/>
        public string destination_msisdn
        {
            get
            {
                return this.destination_msisdnField;
            }
            set
            {
                this.destination_msisdnField = value;
            }
        }

        /// <remarks/>
        public byte delivered_amount_info
        {
            get
            {
                return this.delivered_amount_infoField;
            }
            set
            {
                this.delivered_amount_infoField = value;
            }
        }

        /// <remarks/>
        public byte return_service_fee
        {
            get
            {
                return this.return_service_feeField;
            }
            set
            {
                this.return_service_feeField = value;
            }
        }

        /// <remarks/>
        public string action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
    }
}