using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DeKee.DomainContext.Services.Dto
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "",ElementName ="TransferTo", IsNullable = false)]
    public partial class TopUpResponse
    {

        private string transactionidField;

        private string msisdnField;

        private string destination_msisdnField;

        private string countryField;

        private string countryidField;

        private string operatorField;

        private string reference_operatorField;

        private string operatoridField;

        private string originating_currencyField;

        private string destination_currencyField;

        private string product_requestedField;

        private string actual_product_sentField;

        private string wholesale_priceField;

        private string service_feeField;

        private string retail_priceField;

        private string balanceField;

        private string sms_sentField;

        private string smsField;

        private string sender_smsField;

        private string sender_textField;

        private string cid1Field;

        private string cid2Field;

        private string cid3Field;

        private string authentication_keyField;

        private string error_codeField;

        private string error_txtField;

        private string local_info_valueField;

        private string local_info_amountField;

        private string local_info_currencyField;

        private string return_timestampField;

        private string return_versionField;


        private string pin_basedField;

        private string pin_option_1Field;

        private string pin_option_2Field;

        private string pin_option_3Field;

        private string pin_valueField;

        private string pin_codeField;

        private string pin_ivrField;

        private string pin_serialField;

        /// <remarks/>
        public string transactionid
        {
            get
            {
                return this.transactionidField;
            }
            set
            {
                this.transactionidField = value;
            }
        }

        /// <remarks/>
        public string msisdn
        {
            get
            {
                return this.msisdnField;
            }
            set
            {
                this.msisdnField = value;
            }
        }

        /// <remarks/>
        public string destination_msisdn
        {
            get
            {
                return this.destination_msisdnField;
            }
            set
            {
                this.destination_msisdnField = value;
            }
        }

        /// <remarks/>
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public string countryid
        {
            get
            {
                return this.countryidField;
            }
            set
            {
                this.countryidField = value;
            }
        }

        /// <remarks/>
        public string @operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }

        /// <remarks/>
        public string reference_operator
        {
            get
            {
                return this.reference_operatorField;
            }
            set
            {
                this.reference_operatorField = value;
            }
        }

        /// <remarks/>
        public string operatorid
        {
            get
            {
                return this.operatoridField;
            }
            set
            {
                this.operatoridField = value;
            }
        }

        /// <remarks/>
        public string originating_currency
        {
            get
            {
                return this.originating_currencyField;
            }
            set
            {
                this.originating_currencyField = value;
            }
        }

        /// <remarks/>
        public string destination_currency
        {
            get
            {
                return this.destination_currencyField;
            }
            set
            {
                this.destination_currencyField = value;
            }
        }

        /// <remarks/>
        public string product_requested
        {
            get
            {
                return this.product_requestedField;
            }
            set
            {
                this.product_requestedField = value;
            }
        }

        /// <remarks/>
        public string actual_product_sent
        {
            get
            {
                return this.actual_product_sentField;
            }
            set
            {
                this.actual_product_sentField = value;
            }
        }

        /// <remarks/>
        public string wholesale_price
        {
            get
            {
                return this.wholesale_priceField;
            }
            set
            {
                this.wholesale_priceField = value;
            }
        }

        /// <remarks/>
        public string service_fee
        {
            get
            {
                return this.service_feeField;
            }
            set
            {
                this.service_feeField = value;
            }
        }

        /// <remarks/>
        public string retail_price
        {
            get
            {
                return this.retail_priceField;
            }
            set
            {
                this.retail_priceField = value;
            }
        }

        /// <remarks/>
        public string balance
        {
            get
            {
                return this.balanceField;
            }
            set
            {
                this.balanceField = value;
            }
        }

        /// <remarks/>
        public string sms_sent
        {
            get
            {
                return this.sms_sentField;
            }
            set
            {
                this.sms_sentField = value;
            }
        }

        /// <remarks/>
        public string sms
        {
            get
            {
                return this.smsField;
            }
            set
            {
                this.smsField = value;
            }
        }

        /// <remarks/>
        public string sender_sms
        {
            get
            {
                return this.sender_smsField;
            }
            set
            {
                this.sender_smsField = value;
            }
        }

        /// <remarks/>
        public string sender_text
        {
            get
            {
                return this.sender_textField;
            }
            set
            {
                this.sender_textField = value;
            }
        }

        /// <remarks/>
        public string cid1
        {
            get
            {
                return this.cid1Field;
            }
            set
            {
                this.cid1Field = value;
            }
        }

        /// <remarks/>
        public string cid2
        {
            get
            {
                return this.cid2Field;
            }
            set
            {
                this.cid2Field = value;
            }
        }

        /// <remarks/>
        public string cid3
        {
            get
            {
                return this.cid3Field;
            }
            set
            {
                this.cid3Field = value;
            }
        }

        /// <remarks/>
        public string authentication_key
        {
            get
            {
                return this.authentication_keyField;
            }
            set
            {
                this.authentication_keyField = value;
            }
        }

        /// <remarks/>
        public string error_code
        {
            get
            {
                return this.error_codeField;
            }
            set
            {
                this.error_codeField = value;
            }
        }

        /// <remarks/>
        public string error_txt
        {
            get
            {
                return this.error_txtField;
            }
            set
            {
                this.error_txtField = value;
            }
        }

        /// <remarks/>
        public string local_info_value
        {
            get
            {
                return this.local_info_valueField;
            }
            set
            {
                this.local_info_valueField = value;
            }
        }

        /// <remarks/>
        public string local_info_amount
        {
            get
            {
                return this.local_info_amountField;
            }
            set
            {
                this.local_info_amountField = value;
            }
        }

        /// <remarks/>
        public string local_info_currency
        {
            get
            {
                return this.local_info_currencyField;
            }
            set
            {
                this.local_info_currencyField = value;
            }
        }

        /// <remarks/>
        public string return_timestamp
        {
            get
            {
                return this.return_timestampField;
            }
            set
            {
                this.return_timestampField = value;
            }
        }

        /// <remarks/>
        public string return_version
        {
            get
            {
                return this.return_versionField;
            }
            set
            {
                this.return_versionField = value;
            }
        }


        /// <remarks/>
        public string pin_based
        {
            get
            {
                return this.pin_basedField;
            }
            set
            {
                this.pin_basedField = value;
            }
        }

        /// <remarks/>
        public string pin_option_1
        {
            get
            {
                return this.pin_option_1Field;
            }
            set
            {
                this.pin_option_1Field = value;
            }
        }

        /// <remarks/>
        public string pin_option_2
        {
            get
            {
                return this.pin_option_2Field;
            }
            set
            {
                this.pin_option_2Field = value;
            }
        }

        /// <remarks/>
        public string pin_option_3
        {
            get
            {
                return this.pin_option_3Field;
            }
            set
            {
                this.pin_option_3Field = value;
            }
        }

        /// <remarks/>
        public string pin_value
        {
            get
            {
                return this.pin_valueField;
            }
            set
            {
                this.pin_valueField = value;
            }
        }

        /// <remarks/>
        public string pin_code
        {
            get
            {
                return this.pin_codeField;
            }
            set
            {
                this.pin_codeField = value;
            }
        }

        /// <remarks/>
        public string pin_ivr
        {
            get
            {
                return this.pin_ivrField;
            }
            set
            {
                this.pin_ivrField = value;
            }
        }

        /// <remarks/>
        public string pin_serial
        {
            get
            {
                return this.pin_serialField;
            }
            set
            {
                this.pin_serialField = value;
            }
        }
    }
}
