using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DeKee.DomainContext.Services.Dto
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "",ElementName ="Xml", IsNullable = false)]
    public partial class TopUpRequest
    {

        private string loginField;

        private uint keyField;

        private string md5Field;

        private string msisdnField;

        private string smsField;

        private string destination_msisdnField;

        private string productField;

        private string cid1Field;

        private string sender_smsField;

        private object sender_textField;

        private string delivered_amount_infoField;

        private string return_timestampField;

        private string return_versionField;

        private string return_service_feeField;

        private string actionField;

        /// <remarks/>
        public string login
        {
            get
            {
                return this.loginField;
            }
            set
            {
                this.loginField = value;
            }
        }

        /// <remarks/>
        public uint key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        public string md5
        {
            get
            {
                return this.md5Field;
            }
            set
            {
                this.md5Field = value;
            }
        }

        /// <remarks/>
        public string msisdn
        {
            get
            {
                return this.msisdnField;
            }
            set
            {
                this.msisdnField = value;
            }
        }

        /// <remarks/>
        public string sms
        {
            get
            {
                return this.smsField;
            }
            set
            {
                this.smsField = value;
            }
        }

        /// <remarks/>
        public string destination_msisdn
        {
            get
            {
                return this.destination_msisdnField;
            }
            set
            {
                this.destination_msisdnField = value;
            }
        }

        /// <remarks/>
        public string product
        {
            get
            {
                return this.productField;
            }
            set
            {
                this.productField = value;
            }
        }

        /// <remarks/>
        public string cid1
        {
            get
            {
                return this.cid1Field;
            }
            set
            {
                this.cid1Field = value;
            }
        }

        /// <remarks/>
        public string sender_sms
        {
            get
            {
                return this.sender_smsField;
            }
            set
            {
                this.sender_smsField = value;
            }
        }

        /// <remarks/>
        public object sender_text
        {
            get
            {
                return this.sender_textField;
            }
            set
            {
                this.sender_textField = value;
            }
        }

        /// <remarks/>
        public string delivered_amount_info
        {
            get
            {
                return this.delivered_amount_infoField;
            }
            set
            {
                this.delivered_amount_infoField = value;
            }
        }

        /// <remarks/>
        public string return_timestamp
        {
            get
            {
                return this.return_timestampField;
            }
            set
            {
                this.return_timestampField = value;
            }
        }

        /// <remarks/>
        public string return_version
        {
            get
            {
                return this.return_versionField;
            }
            set
            {
                this.return_versionField = value;
            }
        }

        /// <remarks/>
        public string return_service_fee
        {
            get
            {
                return this.return_service_feeField;
            }
            set
            {
                this.return_service_feeField = value;
            }
        }

        /// <remarks/>
        public string action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        public string ReservedId { get; set; }
    }

}
